name: Deploy

on:
  push:
    branches:
      - 'master'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Modify Procfile
      run: |
        echo "web: ./start.sh" > Procfile
        chmod +x start.sh worker.sh

    - name: Create config.php
      run: echo "$contents" > config.php
      env:
        contents: '${{ secrets.CONFIG_PHP }}'

    - name: Create .env
      run: echo "$contents" > .env
      env:
        contents: '${{ secrets.DOT_ENV }}'

    - name: Cache Composer dependencies
      uses: actions/cache@v2
      with:
        path: /tmp/composer-cache-deploy
        key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

    - name: Install dependencies
      uses: php-actions/composer@v6
      with:
        php_version: "7.4"
        args: --optimize-autoloader --ignore-platform-reqs
        dev: no

    - name: Prepare files
      run: |
        mkdir upload/
        cp -fr bin/ public/ src/ translations/ vendor/ config.php .env upload/
        rm -fr upload/public/.user.ini

    - name: Deploy the application
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASSWORD }}
        protocol: ftp
        local-dir: upload/
        server-dir: ${{ secrets.FTP_DIR }}
