name: Deploy

on:
  push:
    branches:
      - 'master'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Cache Composer dependencies
      uses: actions/cache@v2
      with:
        path: /tmp/composer-cache-deploy
        key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

    - name: Install dependencies
      uses: php-actions/composer@v6
      with:
        php_version: "7.4"
        args: --optimize-autoloader --ignore-platform-reqs
        dev: no

    - name: Create config.php
      env:
        contents: '${{ secrets.CONFIG_PHP }}'
      if: ${{ env.contents != '' }}
      run: echo "$contents" > config.php

    - name: Create .env
      env:
        contents: '${{ secrets.DOT_ENV }}'
      if: ${{ env.contents != '' }}
      run: echo "$contents" > .env

    - name: Prepare files
      run: |
        mkdir upload/
        cp -fr bin/ public/ src/ translations/ vendor/ config.php .env upload/
        rm -fr upload/public/.user.ini

    - name: Deploy the application
      env:
        FTP_SERVER: '${{ secrets.FTP_SERVER }}'
      if: ${{ env.FTP_SERVER != '' }}
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASSWORD }}
        protocol: ${{ secrets.FTP_PROTOCOL }}
        local-dir: upload/
        server-dir: ${{ secrets.FTP_DIR }}
